### ISSUE TITLE
missing xdebug 2.6 for php 7.2

### ISSUE THREAD

**Issue by insekticid** [php-earth/docker-php#13]
xdebug 2.6 for php 7 and 7.1 exists, but not for php 7.2

**Comment by petk** [comment]
Added... Thanks for noticing. It has been missed when packages were uploaded via https://github.com/php-earth/alpine

Xdebug 2.6 is at the moment in Alpha 1 release though but it should work out ok.

**Comment by insekticid** [comment]
whow, very quick response, I will test it

thank you and merry christmas

**Comment by petk** [comment]
Thanks, same to you :+1: :smile:
