### ISSUE TITLE
New extension meminfo for memory leaks detection

### ISSUE THREAD

**Issue by insekticid** [php-earth/docker-php#15]
* https://github.com/BitOne/php-meminfo
* https://gist.github.com/insekticid/95b66b29f0ca6a55055b0be20337f41a

```
RUN curl -L -o /tmp/meminfo.tar.gz https://github.com/BitOne/php-meminfo/archive/master.tar.gz \
    && tar zxpf /tmp/meminfo.tar.gz -C /tmp \
    && rm -r /tmp/meminfo.tar.gz \
    && cd /tmp/php-meminfo-master/extension/php7/ && phpize && ./configure --enable-meminfo && make && make install \
    && rm -rf /tmp/* \
    && printf "extension=meminfo.so\n" > $PHP_INI_DIR/conf.d/meminfo.ini
```

**Comment by petk** [comment]
The `php-meminfo` extension has been added to the [PHP.earth Alpine repo](https://github.com/php-earth/alpine).

Installation:
```bash
apk add --no-cache php7.2-meminfo
```
The docs will be updated in the near future also.

Closing this as resolved and enhanced. In case of issues or questions let me know. Thanks.
