### ISSUE TITLE
PHP 7.2.4

### ISSUE THREAD

**Issue by insekticid** [php-earth/docker-php#17]
http://php.net/ChangeLog-7.php#7.2.4

* Fixed bug #76025 (Segfault while throwing exception in error_handler).

**Comment by petk** [comment]
Expect PHP version bump in a day or so...

**Comment by petk** [comment]
Latest PHP versions are available via these images also. 7a0d3a77d6ed8f843da3ba2ece9b805b8078b6b7 and https://github.com/php-earth/alpine/commit/563a0b697296871830cc0180d37ff8ecc2fd6f15
