### ISSUE TITLE
New extension: AST

### ISSUE THREAD

**Issue by cdaguerre** [php-earth/docker-php#18]
Can anyone explain how to install [php-ast](https://github.com/nikic/php-ast)?
It's required by [phan](https://github.com/phan/phan)

**Comment by petk** [comment]
Hello, the php-ast extension added to PHP.earth Alpine repository via https://github.com/phpearth/alpine/commit/69a3e0b91764ddcb6bf380ea609a8f17bced9588. Installation:

```bash
apk add --no-cache php7.2-ast
```

Or for older PHP versions `apk add --no-cache php7.1-ast` or `apk add --no-cache php7.0-ast`.

In case there are some bugs, let me know. Thanks for reporting.
