### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by adaliszk** [php-earth/docker-php#2]
On the README: "Documentation with Docker and PHP recipes is available on PHP.earth"
The linked page is a 404 page: https://php.earth/doc/docker

I wanted to check that the image has `pdo_firebird` and `interbase` but in the source I only see the commented extension lines in the ini.

**Comment by petk** [comment]
Hello, initial docs have been finally enabled. More improvements coming up in the near future. Stay tuned and thanks for reporting issues.
