### ISSUE TITLE
Certificate phpearth.rsa.pub is expired

### ISSUE THREAD

**Issue by msonowal** [php-earth/docker-php#41]
ADD failed: Get https://repos.php.earth/alpine/phpearth.rsa.pub: x509: certificate has expired or is not yet valid

**Comment by petk** [comment]
Hello, thank you for the report. Renewed.

**Comment by msonowal** [comment]
@petk 
thats really quick thanks a ton

**Comment by smjgithub** [comment]
Is this down again? ADD failed: Get https://repos.php.earth/alpine/phpearth.rsa.pub: Service Unavailable

**Comment by petk** [comment]
@smjgithub it's now working, yes.

**Comment by lvidal1** [comment]
@petk Is it working? Currently, I am getting `ADD failed: Get https://repos.php.earth/alpine/phpearth.rsa.pub: dial tcp 51.15.52.237:443: connect: connection refused`
