### ISSUE TITLE
Problem in Fetching Repo

### ISSUE THREAD

**Issue by ayndev** [php-earth/docker-php#47]
fetch https://repos.php.earth/alpine/v3.9/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://repos.php.earth/alpine/v3.9/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
ERROR: unsatisfiable constraints:

**Comment by Hemric** [comment]
It seems like https://repos.php.earth is down !

**Comment by ayndev** [comment]
Is seems that  https://repos.php.earth  is up again

**Comment by smjgithub** [comment]
> Is seems that https://repos.php.earth is up again

Great, thanks for the update, yes, it is working fine now 👍

**Comment by lvidal1** [comment]
Repo is down again. I am getting a message saying `Get https://repos.php.earth/alpine/phpearth.rsa.pub: dial tcp 51.15.52.237:443: connect: connection refused` while building an image. Can someone know when it will be available again?
