### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by archer-developer** [php-earth/docker-php#48]
Hello!
We are using phpearth/php:7.3-nginx docker image and we had a problem during building containers. SSL certificate in https://repos.php.earth is expired today (2 March). Please, renew SSL certificate.

**Comment by OlegBabakov** [comment]
`139656898775912:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915:
ERROR: http://repos.php.earth/alpine/v3.9: Permission denied
`

Got SSL error again
Could you help?

**Comment by archer-developer** [comment]
Hello, guys!
I maked a simple hotfix. I changed repository url (from base image) to my proxy. I added proxy to my dockerfile:

```
FROM phpearth/php:7.3-nginx

# Change repositories to alternative: see https://github.com/phpearth/docker-php/issues/48
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.9/main" > /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.9/community" >> /etc/apk/repositories
RUN apk --update add ca-certificates
RUN echo "<INSERT YOUR SERVER DOMAIN HERE>/alpine/v3.9" >> /etc/apk/repositories
RUN apk upgrade --update-cache --available
 
```
On my server I placed simple script (phpearth.php):

```
<?php
system('wget -O - https://repos.php.earth'.$_SERVER['REQUEST_URI'].' --no-check-certificate');

```

Apache configuration:
```

<VirtualHost *:80>
    ServerName <YOUR SERVER DOMAIN>

    DocumentRoot /var/www/html
    DirectoryIndex /phpearth.php

    <Directory /var/www/html>
        AllowOverride None
        Order Allow,Deny
        Allow from All
        Require all granted

        FallbackResource /phpearth.php
    </Directory>        
</VirtualHost>

```
Hope this helps
